language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libusb-1.0-0-dev
    - blibxrandr-dev
    - libxi-dev
    - libxxf86vm-dev
    
before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev

script:
  - make
